### PR TITLE
Update to v1.5.18

### PR DESCRIPTION
**Pull request by tkelman**
closes #12

### CODE REVIEW

**Comment by isuruf** [comment]
@tkelman, do you want to be a maintainer for this recipe?

**Comment by tkelman** [comment]
I'll take a few days' silence as a "don't mind" ?

**Comment by proinsias** [comment]
Apologies for the radio silence. Happy to have more maintainers.

**Comment by tkelman** [comment]
Cool, no problem. Guess you're not on the botocore-feedstock maintainers list, but a newer version here would be blocked on https://github.com/conda-forge/botocore-feedstock/pull/35

**Pull request merged**
