### PR TITLE
fix requirement bounds to match upstream setup.py

### PR DESCRIPTION
**Pull request by tkelman**
ref https://github.com/boto/boto3/blob/1.5.14/setup.py#L17-L19

increment build to 1

### CODE REVIEW

**Comment by tkelman** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@tkelman, you need to rebase. Since this recipe is noarch now, it'll only test in circle-ci

**Comment by tkelman** [comment]
replaced by #14

**Pull request closed without merging**
