### PR TITLE
Update to 1.5.6

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by proinsias** [comment]
Rerunning AppVeyor.

**Comment by sannykr** [comment]
@proinsias: Thanks. I think I had already tried to rerun appveyor but that was not the issue. I have re-rendered the feedstock, and now it should be fine.

**Comment by sannykr** [comment]
@proinsias : Thanks for notifying.

**Comment by proinsias** [comment]
@sannykr – Apparently the conda-forge AppVeyor builds are down in general. So I don't think this failure should be a blocker. I'm just waiting on Travis.

**Pull request merged**
