### PR TITLE
changed the build number and made it a noarch

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@proinsias: I have made it a noarch and now only circleci check is enough to be merged. Can you please merge it now.

**Comment by isuruf** [comment]
@sannykr, when you make a feedstock noarch, you have to rerender.
@conda-forge-admin, please rerender

**Comment by sannykr** [comment]
@isuruf : Thanks.

**Comment by sannykr** [comment]
@proinsias : Could you please merge it.

**Comment by proinsias** [comment]
Thanks @sannykr – interested in becoming a maintainer?

**Pull request merged**
